# Generated by Django 5.0.7 on 2024-08-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TIPO1', 'liquido'), ('TIPO2', 'etiqueta'), ('TIPO3', 'miscelanea'), ('TIPO4', 'paquete'), ('TIPO5', 'envase')], max_length=10)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('sku', models.CharField(max_length=45)),
                ('volumen', models.PositiveIntegerField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('fragancia', models.CharField(max_length=45, null=True)),
                ('volumen', models.IntegerField(null=True)),
                ('stock_producto', models.IntegerField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liquido', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_liquido', models.CharField(choices=[('TIP1', 'esencia'), ('TIP2', 'fragancia'), ('TIP3', 'agua'), ('TIP4', 'alcohol')], max_length=45)),
                ('volumen', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miscelanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=45)),
                ('nombre_objeto', models.CharField(max_length=45)),
                ('tipo_objeto', models.CharField(choices=[('TIPO1', 'varilla'), ('TIPO2', 'lampara'), ('TIPO3', 'colgante'), ('TIPO4', 'accesorio')], max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendible', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_paquete', models.CharField(choices=[('TIPO1', 'caja'), ('TIPO2', 'bolsa')], max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volumen', models.PositiveIntegerField()),
                ('id_liquido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.liquido')),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_envase', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_envase', models.CharField(choices=[('TIPO1', 'bidon'), ('TIPO2', 'PET'), ('TIPO3', 'difusor'), ('TIPO4', 'jarabe'), ('TIPO4', 'colirio')], max_length=45)),
                ('volumen', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_liquido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.liquido')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envase')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('producto', 'envase')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='envases',
            field=models.ManyToManyField(through='api.ProductoEnvase', to='api.envase'),
        ),
        migrations.CreateModel(
            name='ProductoMiscelanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscelanea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.miscelanea')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('producto', 'miscelanea')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='miscelaneas',
            field=models.ManyToManyField(through='api.ProductoMiscelanea', to='api.miscelanea'),
        ),
        migrations.CreateModel(
            name='ProductoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paquete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('producto', 'paquete')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='paquetes',
            field=models.ManyToManyField(through='api.ProductoPaquete', to='api.paquete'),
        ),
    ]
