# Generated by Django 5.0.7 on 2024-07-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_insumo', models.CharField(choices=[('TIPO1', 'Tipo 1'), ('TIPO2', 'Tipo 2')], max_length=45)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Liquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liquido', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_liquido', models.CharField(choices=[('TIPO1', 'Tipo 1'), ('TIPO2', 'Tipo 2')], max_length=45)),
                ('volumen', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miscelanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=45)),
                ('nombre_objeto', models.CharField(max_length=45)),
                ('tipo_objeto', models.CharField(choices=[('TIPO1', 'Tipo 1'), ('TIPO2', 'Tipo 2')], max_length=45)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('volumen', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_liquido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.liquido')),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=45)),
                ('tipo_envase', models.CharField(choices=[('TIPO1', 'Tipo 1'), ('TIPO2', 'Tipo 2')], max_length=45)),
                ('volumen', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etiqueta')),
                ('id_liquido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.liquido')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_paquete', models.CharField(choices=[('TIPO1', 'Tipo 1'), ('TIPO2', 'Tipo 2')], max_length=45)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_envase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.envase')),
                ('id_objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.miscelanea')),
                ('id_paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paquete')),
            ],
        ),
    ]
