# Generated by Django 5.0.7 on 2024-08-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoView',
            fields=[
                ('tipo', models.CharField(max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('sku', models.CharField(max_length=45)),
                ('tipo_especifico', models.CharField(max_length=45)),
                ('volumen', models.IntegerField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMiscelanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscelanea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.miscelanea')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.RemoveField(
            model_name='envase',
            name='id_etiqueta',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='id_etiqueta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_envase',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_objeto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_paquete',
        ),
        migrations.AddField(
            model_name='envase',
            name='nombre_envase',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envase',
            name='id_liquido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.liquido'),
        ),
        migrations.AddField(
            model_name='productoenvase',
            name='envase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envase'),
        ),
        migrations.AddField(
            model_name='productoenvase',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='envases',
            field=models.ManyToManyField(through='api.ProductoEnvase', to='api.envase'),
        ),
        migrations.AddField(
            model_name='productomiscelanea',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='miscelaneas',
            field=models.ManyToManyField(through='api.ProductoMiscelanea', to='api.miscelanea'),
        ),
        migrations.AddField(
            model_name='productopaquete',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paquete'),
        ),
        migrations.AddField(
            model_name='productopaquete',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='paquetes',
            field=models.ManyToManyField(through='api.ProductoPaquete', to='api.paquete'),
        ),
        migrations.AlterUniqueTogether(
            name='productoenvase',
            unique_together={('producto', 'envase')},
        ),
        migrations.AlterUniqueTogether(
            name='productomiscelanea',
            unique_together={('producto', 'miscelanea')},
        ),
        migrations.AlterUniqueTogether(
            name='productopaquete',
            unique_together={('producto', 'paquete')},
        ),
    ]
