# Generated by Django 5.0.7 on 2024-08-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envase',
            name='tipo_envase',
            field=models.CharField(choices=[('Bidon', 'bidon'), ('PET', 'PET'), ('Difusor', 'difusor'), ('Jarabe', 'jarabe'), ('Colirio', 'colirio')], max_length=45),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='tipo_liquido',
            field=models.CharField(choices=[('Esencia', 'esencia'), ('Fragancia', 'fragancia'), ('Agua', 'agua'), ('Alcohol', 'alcohol')], max_length=45),
        ),
        migrations.AlterField(
            model_name='miscelanea',
            name='tipo_objeto',
            field=models.CharField(choices=[('Varilla', 'varilla'), ('Lampara', 'lampara'), ('Colgante', 'colgante'), ('Accesorio', 'accesorio')], max_length=45),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='tipo_paquete',
            field=models.CharField(choices=[('Caja', 'caja'), ('Bolsa', 'bolsa')], max_length=45),
        ),
    ]
