# Generated by Django 5.0.7 on 2024-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_insumoview_productoenvase_productomiscelanea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('sku', models.CharField(max_length=45)),
                ('fragancia', models.CharField(max_length=45, null=True)),
                ('volumen', models.IntegerField(null=True)),
                ('stock_producto', models.IntegerField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='miscelanea',
            name='vendible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='envase',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='envase',
            name='tipo_envase',
            field=models.CharField(choices=[('TIPO1', 'PET'), ('TIPO2', 'vidrio')], max_length=45),
        ),
        migrations.AlterField(
            model_name='envase',
            name='volumen',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='volumen',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='tipo_liquido',
            field=models.CharField(choices=[('TIP1', 'esencia'), ('TIP2', 'fragancia'), ('TIP3', 'agua'), ('TIP4', 'alcohol')], max_length=45),
        ),
        migrations.AlterField(
            model_name='miscelanea',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='miscelanea',
            name='tipo_objeto',
            field=models.CharField(choices=[('TIPO1', 'varilla'), ('TIPO2', 'lampara'), ('TIPO3', 'colgante'), ('TIPO4', 'accesorio')], max_length=45),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='tipo_paquete',
            field=models.CharField(choices=[('TIPO1', 'caja'), ('TIPO2', 'bolsa')], max_length=45),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
