# Generated by Django 5.0.7 on 2024-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productosview_miscelanea_vendible_alter_envase_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envase',
            name='tipo_envase',
            field=models.CharField(choices=[('TIPO1', 'bidon'), ('TIPO2', 'PET'), ('TIPO3', 'difusor'), ('TIPO4', 'jarabe'), ('TIPO4', 'colirio')], max_length=45),
        ),
    ]
