# Generated by Django 5.0.7 on 2024-08-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_envase_tipo_envase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscelanea',
            name='vendible',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
